spring:
  application:
    name: products
  datasource:
    url: jdbc:postgresql://localhost:5433/productsdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8082