spring:
  application:
    name: products
  datasource:
    url: jdbc:postgresql://localhost:5432/productsdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082