spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5434/authdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

jwt:
  secret: TXA7lA9WcZ0+fq5iyLkJjXBgGf0VKySkSsqFhyBvazk=
  expiration: 3600000

